### ISSUE TITLE
Remove color coding? codes from syslog* messages

### ISSUE THREAD

**Issue by florianpiekert** [Zuplu/postfix-tlspol#32]
ubuntu 24.01.... rsyslogd

Mar  8 12:46:20 sonne postfix-tlspol[3373864]: postfix-tlspol (c) 2024-2025 Zuplu <E2><80><94> v1.7.3-6-g6941720
Mar  8 12:46:20 sonne postfix-tlspol[3373864]: This program is licensed under the MIT License.
Mar  8 12:46:20 sonne postfix-tlspol[3373864]: #033[92mINFO  Prefetching enabled!#033[0m
Mar  8 12:46:20 sonne postfix-tlspol[3373864]: #033[90mDEBUG Listening on 127.0.0.1:8642...#033[0m

When rsyslog receives an stores the messages, some additional codes, e.g.
#033[92m
are provided in the message.

Please remove them or make it configurable (disable-option?).

**Comment by DragonWork** [comment]
Maybe fixed in v1.8.0. Please check first before closing.
Colored logs are supported by systemd-journald and won‘t be printed if another logging service is used.

**Comment by florianpiekert** [comment]
It is not yet fixed from my observation:
Mar  9 09:27:31 sonne postfix-tlspol[4170889]: postfix-tlspol (c) 2024-2025 Zuplu â v1.8.0
Mar  9 09:27:31 sonne postfix-tlspol[4170889]: This program is licensed under the MIT License.
Mar  9 09:27:31 sonne postfix-tlspol[4170889]: #033[92mINFO  Prefetching enabled!#033[0m
Mar  9 09:27:31 sonne postfix-tlspol[4170889]: #033[92mINFO  Listening on 127.0.0.1:8642...#033[0m
Mar  9 09:30:03 sonne postfix-tlspol[4170889]: #033[92mINFO  Evaluated policy for "charite.de": secure match=mail-cbf-ext.charite.de:mail-cvk-ext.charite.de servername=hostname (cached for 1209600s)#033[0m

**Comment by DragonWork** [comment]
With the latest commit, if the autodetection still doesn't work, you can run `systemctl edit postfix-tlspol.service` and add following:

```
[Service]
Environment="NO_COLOR=1"
```

It is important that you don't edit the `postfix-tlspol.service` file directly, because it can be overriden.
